import { Effect } from "effect";

/**
 * Wrap an effect with a span for tracing
 */
export const withSpan =
  (name: string, attributes?: Record<string, unknown>) =>
  <A, E, R>(effect: Effect.Effect<A, E, R>): Effect.Effect<A, E, R> =>
    Effect.withSpan(name, { attributes })(effect);

/**
 * Common span names for RPC operations
 */
export const SpanNames = {
  BALANCE_CHECK: "ew3.balance.check",
  BALANCE_CHECK_TOKEN: "ew3.balance.checkToken",
  BALANCE_GET: "ew3.balance.get",
  BALANCE_GET_TOKEN: "ew3.balance.getToken",
  BALANCE_GET_TOKEN_BATCH: "ew3.balance.getTokenBatch",
  BALANCE_WATCH: "ew3.balance.watch",
  BALANCE_WATCH_TOKEN: "ew3.balance.watchToken",
  BLOCK_GET: "ew3.block.get",
  BLOCK_GET_BY_HASH: "ew3.block.getByHash",
  BLOCK_GET_NUMBER: "ew3.block.getNumber",
  BLOCK_GET_RANGE: "ew3.block.getRange",
  BLOCK_GET_TIMESTAMP: "ew3.block.getTimestamp",
  BLOCK_WAIT: "ew3.block.wait",
  BLOCK_WATCH: "ew3.block.watch",
  CONTRACT_ESTIMATE_GAS: "ew3.contract.estimateGas",
  CONTRACT_READ: "ew3.contract.read",
  CONTRACT_SIMULATE: "ew3.contract.simulate",
  CONTRACT_WRITE: "ew3.contract.write",
  CROSS_CHAIN_MULTICALL_ALL: "ew3.crossChain.multicallAll",
  CROSS_CHAIN_READ_ALL: "ew3.crossChain.readAll",
  CROSS_CHAIN_READ_SAME: "ew3.crossChain.readSame",
  DEPLOY_COMPUTE_ADDRESS: "ew3.deploy.computeAddress",
  DEPLOY_CONTRACT: "ew3.deploy.contract",
  DEPLOY_VERIFY: "ew3.deploy.verify",
  ENS_GET_ADDRESS: "ew3.ens.getAddress",
  ENS_GET_AVATAR: "ew3.ens.getAvatar",
  ENS_GET_NAME: "ew3.ens.getName",
  ENS_GET_RESOLVER: "ew3.ens.getResolver",
  ENS_GET_TEXT: "ew3.ens.getText",
  ERC721_APPROVE: "ew3.erc721.approve",
  ERC721_BALANCE_OF: "ew3.erc721.balanceOf",
  ERC721_FETCH_METADATA: "ew3.erc721.fetchMetadata",
  ERC721_GET_APPROVED: "ew3.erc721.getApproved",
  ERC721_IS_APPROVED_FOR_ALL: "ew3.erc721.isApprovedForAll",
  ERC721_NAME: "ew3.erc721.name",
  ERC721_OWNER_OF: "ew3.erc721.ownerOf",
  ERC721_SAFE_TRANSFER_FROM: "ew3.erc721.safeTransferFrom",
  ERC721_SET_APPROVAL_FOR_ALL: "ew3.erc721.setApprovalForAll",
  ERC721_SYMBOL: "ew3.erc721.symbol",
  ERC721_TOKEN_URI: "ew3.erc721.tokenURI",
  ERC721_TOTAL_SUPPLY: "ew3.erc721.totalSupply",
  ERC721_TRANSFER_FROM: "ew3.erc721.transferFrom",
  EVENT_BACKFILL: "ew3.event.backfill",
  EVENT_WATCH: "ew3.event.watch",
  GAS_ESTIMATE_FEES: "ew3.gas.estimateFees",
  GAS_ESTIMATE_GAS: "ew3.gas.estimateGas",
  GAS_GET_ALL_ESTIMATES: "ew3.gas.getAllEstimates",
  GAS_GET_BASE_FEE: "ew3.gas.getBaseFee",
  GAS_GET_MAX_PRIORITY_FEE: "ew3.gas.getMaxPriorityFee",
  GAS_SUPPORTS_EIP1559: "ew3.gas.supportsEip1559",
  MULTICALL: "ew3.contract.multicall",
  NONCE_CONFIRM: "ew3.nonce.confirm",
  NONCE_GET_CONFIRMED_COUNT: "ew3.nonce.getConfirmedCount",
  NONCE_GET_GAPS: "ew3.nonce.getGaps",
  NONCE_GET_NEXT: "ew3.nonce.getNext",
  NONCE_GET_PENDING_COUNT: "ew3.nonce.getPendingCount",
  NONCE_RELEASE: "ew3.nonce.release",
  NONCE_RESERVE: "ew3.nonce.reserve",
  NONCE_SYNC: "ew3.nonce.sync",
  SAFE_ENABLE_OFFCHAIN: "ew3.safe.enableOffchainSigning",

  // Safe Apps
  SAFE_GET_INFO: "ew3.safe.getInfo",
  SAFE_GET_OFFCHAIN_SIG: "ew3.safe.getOffchainSignature",
  SAFE_GET_TX: "ew3.safe.getTransaction",
  SAFE_POLL_OFFCHAIN_SIG: "ew3.safe.pollOffchainSignature",
  SAFE_SEND_TXS: "ew3.safe.sendTransactions",
  SAFE_SIGN_TYPED_DATA: "ew3.safe.signTypedData",
  SAFE_WAIT_RECEIPT: "ew3.safe.waitForReceipt",
  SIGNATURE_HASH_MESSAGE: "ew3.signature.hashMessage",
  SIGNATURE_HASH_TYPED_DATA: "ew3.signature.hashTypedData",
  SIGNATURE_JOIN: "ew3.signature.join",
  SIGNATURE_RECOVER_ADDRESS: "ew3.signature.recoverAddress",
  SIGNATURE_RECOVER_TYPED_DATA_ADDRESS: "ew3.signature.recoverTypedDataAddress",
  SIGNATURE_SPLIT: "ew3.signature.split",
  SIGNATURE_VERIFY_MESSAGE: "ew3.signature.verifyMessage",
  SIGNATURE_VERIFY_TYPED_DATA: "ew3.signature.verifyTypedData",
  SIMULATION_SIMULATE: "ew3.simulation.simulate",
  SIMULATION_SIMULATE_BUNDLE: "ew3.simulation.simulateBundle",
  SUBSCRIPTION_WATCH_BLOCKS: "ew3.subscription.watchBlocks",
  SUBSCRIPTION_WATCH_LOGS: "ew3.subscription.watchLogs",
  SUBSCRIPTION_WATCH_PENDING_TX: "ew3.subscription.watchPendingTx",
  TRANSFER_ESTIMATE: "ew3.transfer.estimateGas",
  TRANSFER_SEND: "ew3.transfer.send",
  TRANSFER_SEND_AND_WAIT: "ew3.transfer.sendAndWait",
  TX_GET_CONFIRMATIONS: "ew3.tx.getConfirmations",
  TX_TRACK: "ew3.tx.track",
  TX_WAIT: "ew3.tx.wait",
  WALLET_CONNECT: "ew3.wallet.connect",
  WALLET_SIGN_MESSAGE: "ew3.wallet.signMessage",
  WALLET_SIGN_TYPED_DATA: "ew3.wallet.signTypedData",
} as const;
