name: web3 > CI

on:
  push: &web3_filters
    branches: [main]
    paths:
      # == Workspace configs ==
      - "**/*.just"
      - "**/justfile"
      - .prettierrc.js
      - biome.jsonc
      - bun.lock
      - bunfig.toml
      - package.json
      - tsconfig.json
      # == Package-specific ==
      - "web3/**"
      - "**/web3.*.yml"
  pull_request: *web3_filters

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/_base.ci.yml
    with:
      package-name: web3
